# Target specific macros
TARGET = FOLLOW_CAR
TARGET_SOURCES = \
	follow_car.c
TOPPERS_OSEK_OIL_SOURCE = ./follow_car.oil

# Don't modify below part
O_PATH ?= build
include /home/osek/nxtOSEK/ecrobot/ecrobot.mak
