# Target specific macros
TARGET = CONTROL_CAR
TARGET_SOURCES = \
	control_car.c
TOPPERS_OSEK_OIL_SOURCE = ./control_car.oil

# Don't modify below part
O_PATH ?= build
include /home/osek/nxtOSEK/ecrobot/ecrobot.mak
